window.DEV_SYSTEM_GLOSARIO = [
  { termino: "CPU", variantes: ["procesador"], definicion: "El cerebro de la computadora: ejecuta las instrucciones de los programas.", mes: 1 },
  { termino: "RAM", variantes: ["memoria"], definicion: "La mesa de trabajo de la computadora: guarda lo que está en uso; se vacía al apagar.", mes: 1 },
  { termino: "disco", variantes: ["almacenamiento", "SSD", "disco duro"], definicion: "Donde viven los archivos de forma permanente.", mes: 1 },
  { termino: "bit", variantes: ["bits"], definicion: "La unidad mínima de información digital: un 1 o un 0.", mes: 1 },
  { termino: "byte", variantes: ["bytes"], definicion: "8 bits juntos; alcanza para guardar una letra.", mes: 1 },
  { termino: "extensión", variantes: ["extension"], definicion: "El \"apellido\" de un archivo (.html, .js, .png): dice qué tipo de contenido tiene.", mes: 1 },
  { termino: "ruta", variantes: ["path", "directorio"], definicion: "La dirección exacta de un archivo dentro de las carpetas.", mes: 1 },
  { termino: "terminal", variantes: ["consola", "línea de comandos", "CLI"], definicion: "La pantalla donde se le dan órdenes escritas (comandos) a la computadora.", mes: 1 },
  { termino: "comando", variantes: ["comandos"], definicion: "Una orden escrita que se ejecuta en la terminal.", mes: 1 },
  { termino: "prompt", variantes: [], definicion: "Lo que le escribes a una IA para pedirle algo. También: el símbolo de la terminal esperando órdenes.", mes: 1 },
  { termino: "sistema operativo", variantes: ["OS", "windows", "macos"], definicion: "El programa jefe que administra toda la computadora.", mes: 1 },
  { termino: "Linux", variantes: ["ubuntu"], definicion: "Sistema operativo gratuito que corre en la mayoría de los servidores de internet.", mes: 1 },
  { termino: "dependencia", variantes: ["dependencias", "librería", "libreria", "library"], definicion: "Pieza de código ya hecha que un proyecto necesita para funcionar.", mes: 1 },
  { termino: "versión", variantes: ["version", "versiones"], definicion: "Número que identifica cada edición de un programa o pieza (1.0, 2.3…).", mes: 1 },
  { termino: "npm", variantes: [], definicion: "La \"tienda\" de piezas de JavaScript: instala las dependencias de un proyecto.", mes: 1 },
  { termino: "package.json", variantes: [], definicion: "El archivo que lista qué dependencias (y versiones) usa un proyecto.", mes: 1 },
  { termino: "caché", variantes: ["cache"], definicion: "Copia temporal de datos para que algo cargue más rápido la próxima vez.", mes: 1 },
  { termino: "IP", variantes: ["dirección ip"], definicion: "El número único que identifica a cada dispositivo en una red.", mes: 1 },
  { termino: "DNS", variantes: [], definicion: "El directorio telefónico de internet: convierte nombres (google.com) en direcciones IP.", mes: 9 },
  { termino: "URL", variantes: ["link", "enlace"], definicion: "La dirección de una página o recurso en internet.", mes: 1 },
  { termino: "HTTP", variantes: ["https"], definicion: "El protocolo con el que viajan las páginas web. La S es la versión segura (cifrada).", mes: 4 },
  { termino: "cliente", variantes: [], definicion: "El que pide: tu navegador o app pidiendo datos a un servidor.", mes: 4 },
  { termino: "servidor", variantes: ["server"], definicion: "Computadora que responde peticiones: entrega páginas, datos, archivos.", mes: 9 },
  { termino: "la nube", variantes: ["nube", "cloud"], definicion: "Servidores de otra empresa que rentas por internet.", mes: 9 },
  { termino: "ancho de banda", variantes: ["bandwidth"], definicion: "Cuánta información puede viajar por tu conexión por segundo.", mes: 1 },
  { termino: "puerto", variantes: ["puertos"], definicion: "Puerta numerada de un servidor: cada servicio atiende en un número (80, 443, 3000).", mes: 9 },
  { termino: "localhost", variantes: [], definicion: "Tu propia computadora actuando como servidor, para probar antes de publicar.", mes: 3 },
  { termino: "2FA", variantes: ["autenticación de dos factores", "mfa"], definicion: "Verificación doble al iniciar sesión (contraseña + código). Actívala en todo.", mes: 10 },
  { termino: "phishing", variantes: [], definicion: "Estafa que imita sitios o correos legítimos para robarte claves.", mes: 10 },
  { termino: "programar", variantes: ["programación"], definicion: "Escribir instrucciones para que una computadora haga algo.", mes: 1 },
  { termino: "lenguaje de programación", variantes: ["lenguaje"], definicion: "Idioma con reglas estrictas para darle instrucciones a la computadora.", mes: 1 },
  { termino: "JavaScript", variantes: ["js"], definicion: "El lenguaje de la web: corre en todos los navegadores. NO es lo mismo que Java.", mes: 1 },
  { termino: "Java", variantes: [], definicion: "Lenguaje de sistemas grandes (bancos, Android). Solo comparte nombre con JavaScript.", mes: 1 },
  { termino: "Python", variantes: [], definicion: "Lenguaje favorito de la IA y el análisis de datos; famoso por ser legible.", mes: 1 },
  { termino: "SQL", variantes: [], definicion: "El lenguaje para hablar con bases de datos: buscar, guardar, modificar, borrar.", mes: 1 },
  { termino: "HTML", variantes: [], definicion: "El esqueleto de toda página web: define qué hay y en qué orden.", mes: 3 },
  { termino: "CSS", variantes: ["estilos"], definicion: "El estilista de la web: colores, tamaños, posiciones.", mes: 3 },
  { termino: "variable", variantes: ["variables"], definicion: "Cajita con nombre donde un programa guarda un dato.", mes: 1 },
  { termino: "booleano", variantes: ["boolean"], definicion: "Tipo de dato con solo dos valores: verdadero o falso.", mes: 1 },
  { termino: "condicional", variantes: ["if", "if/else"], definicion: "Código que toma decisiones: \"si pasa esto, haz aquello\".", mes: 1 },
  { termino: "ciclo", variantes: ["loop", "for", "while"], definicion: "Código que repite una acción muchas veces sin cansarse.", mes: 1 },
  { termino: "función", variantes: ["function", "funciones"], definicion: "Receta reutilizable de código: recibe ingredientes, entrega un resultado.", mes: 1 },
  { termino: "parámetro", variantes: ["parametros", "argumento"], definicion: "El \"ingrediente\" que le pasas a una función.", mes: 1 },
  { termino: "arreglo", variantes: ["array", "lista"], definicion: "Muchos valores guardados en una sola variable, en orden.", mes: 1 },
  { termino: "objeto", variantes: ["objetos"], definicion: "Ficha con datos relacionados (nombre, precio, teléfono) agrupados.", mes: 1 },
  { termino: "JSON", variantes: [], definicion: "El formato en el que viajan los datos por internet: texto con estructura de fichas.", mes: 1 },
  { termino: "bug", variantes: ["bugs", "error"], definicion: "Comportamiento equivocado de un programa. Se arregla \"debuggeando\".", mes: 8 },
  { termino: "debug", variantes: ["debuggear", "debugging"], definicion: "Encontrar y corregir la causa de un bug, con método.", mes: 8 },
  { termino: "framework", variantes: ["frameworks"], definicion: "Esqueleto prearmado para construir apps sin empezar de cero (React, Next.js…).", mes: 3 },
  { termino: "algoritmo", variantes: ["algoritmos"], definicion: "Receta paso a paso para resolver un problema.", mes: 1 },
  { termino: "API", variantes: ["apis"], definicion: "El \"mesero\" entre dos sistemas: recibe peticiones, trae respuestas.", mes: 4 },
  { termino: "REST", variantes: ["endpoint"], definicion: "Estilo estándar de APIs web; un endpoint es cada \"ventanilla\" de la API.", mes: 4 },
  { termino: "base de datos", variantes: ["db", "database"], definicion: "Donde viven los datos de un sistema: clientes, ventas, alumnos.", mes: 4 },
  { termino: "open source", variantes: ["código abierto"], definicion: "Software cuyo código es público: cualquiera lo puede leer, usar y mejorar.", mes: 2 },
  { termino: "frontend", variantes: [], definicion: "La parte visible de una app: lo que el usuario ve y toca.", mes: 3 },
  { termino: "backend", variantes: [], definicion: "La parte invisible: servidores, lógica de negocio y datos.", mes: 4 },
  { termino: "repositorio", variantes: ["repo", "repos"], definicion: "La carpeta de un proyecto con memoria: guarda el código y todo su historial.", mes: 2 },
  { termino: "Git", variantes: [], definicion: "El sistema que registra cada cambio de un proyecto y permite volver atrás.", mes: 2 },
  { termino: "GitHub", variantes: [], definicion: "La plataforma donde viven los repositorios en internet (la red social del código).", mes: 2 },
  { termino: "commit", variantes: ["commits"], definicion: "Una \"fotografía\" del proyecto en un momento: qué cambió y por qué.", mes: 2 },
  { termino: "branch", variantes: ["rama", "branches"], definicion: "Copia paralela del proyecto para trabajar sin romper la versión principal.", mes: 2 },
  { termino: "merge", variantes: ["mergear"], definicion: "Unir los cambios de una rama con otra.", mes: 2 },
  { termino: "pull request", variantes: ["PR"], definicion: "Propuesta de cambios lista para revisión antes de unirse al proyecto.", mes: 2 },
  { termino: "clone", variantes: ["clonar"], definicion: "Descargar una copia completa de un repositorio a tu computadora.", mes: 2 },
  { termino: "push", variantes: [], definicion: "Subir tus commits de tu computadora al repositorio en internet.", mes: 2 },
  { termino: "README", variantes: [], definicion: "El documento de bienvenida de un repo: qué es el proyecto y cómo usarlo.", mes: 2 },
  { termino: "DOM", variantes: [], definicion: "El mapa vivo de una página que JavaScript puede leer y modificar.", mes: 3 },
  { termino: "responsive", variantes: [], definicion: "Diseño que se adapta bien a cualquier pantalla: celular, tablet, compu.", mes: 3 },
  { termino: "React", variantes: [], definicion: "El framework de frontend más usado del mundo; construye interfaces por componentes.", mes: 3 },
  { termino: "componente", variantes: ["componentes"], definicion: "Pieza reutilizable de interfaz: un botón, una card, un menú.", mes: 3 },
  { termino: "autenticación", variantes: ["auth", "login"], definicion: "Verificar quién eres (contraseña, código, huella) para entrar a un sistema.", mes: 4 },
  { termino: "token", variantes: ["tokens"], definicion: "Credencial temporal que prueba tu identidad ante un sistema. En IA: pedacito de palabra.", mes: 5 },
  { termino: "cookie", variantes: ["cookies"], definicion: "Datito que una página guarda en tu navegador para recordarte.", mes: 4 },
  { termino: "LLM", variantes: ["modelo de lenguaje"], definicion: "IA entrenada con cantidades masivas de texto; el motor de ChatGPT, Claude y Gemini.", mes: 5 },
  { termino: "alucinación", variantes: ["alucinaciones", "hallucination"], definicion: "Cuando la IA da información falsa con total confianza. Verifica los datos críticos.", mes: 5 },
  { termino: "ventana de contexto", variantes: ["contexto"], definicion: "La memoria de trabajo de una conversación con IA; tiene límite y se llena.", mes: 5 },
  { termino: "fine-tuning", variantes: [], definicion: "Re-entrenar un modelo de IA con datos propios para especializarlo.", mes: 5 },
  { termino: "RAG", variantes: [], definicion: "Técnica para que la IA consulte tus documentos antes de responder.", mes: 5 },
  { termino: "agente", variantes: ["agentes", "agent"], definicion: "IA que no solo responde: ejecuta pasos por sí misma usando herramientas.", mes: 6 },
  { termino: "Claude Code", variantes: [], definicion: "Herramienta de Anthropic: un agente de IA que programa desde la terminal.", mes: 6 },
  { termino: "Cursor", variantes: [], definicion: "Editor de código con IA integrada en todo el flujo.", mes: 6 },
  { termino: "Copilot", variantes: [], definicion: "El asistente de IA de GitHub que autocompleta y sugiere código.", mes: 6 },
  { termino: "hook", variantes: ["hooks"], definicion: "Código que se dispara automáticamente cuando ocurre un evento (\"cuando pase X, haz Y\").", mes: 6 },
  { termino: "skill", variantes: ["skills"], definicion: "Instrucciones empaquetadas que le enseñan a un agente de IA a hacer una tarea específica.", mes: 6 },
  { termino: "slash command", variantes: ["comando slash"], definicion: "Atajo que empieza con \"/\" para pedirle algo predefinido a una herramienta de IA.", mes: 6 },
  { termino: "MCP", variantes: ["model context protocol"], definicion: "Protocolo que conecta una IA con sistemas externos (bases de datos, WhatsApp, Sheets…).", mes: 7 },
  { termino: "webhook", variantes: ["webhooks"], definicion: "Aviso automático entre sistemas: \"cuando pase algo aquí, notifica allá\".", mes: 11 },
  { termino: "integración", variantes: ["integraciones"], definicion: "Conectar dos sistemas para que trabajen juntos.", mes: 7 },
  { termino: "testing", variantes: ["test", "pruebas"], definicion: "Verificar que el software hace lo que debe, antes de que lo usen clientes.", mes: 8 },
  { termino: "code review", variantes: ["revisión de código"], definicion: "Revisar código (propio, ajeno o de la IA) antes de aceptarlo al proyecto.", mes: 8 },
  { termino: "spec", variantes: ["brief", "especificación"], definicion: "Documento que define QUÉ se va a construir antes de construirlo.", mes: 8 },
  { termino: "deploy", variantes: ["deployar", "despliegue"], definicion: "Publicar tu aplicación para que el mundo la pueda usar.", mes: 9 },
  { termino: "hosting", variantes: [], definicion: "El servicio que aloja tu página/app en internet.", mes: 9 },
  { termino: "dominio", variantes: ["dominios"], definicion: "El nombre propio de tu sitio (tunegocio.com); se renta por año.", mes: 9 },
  { termino: "Netlify", variantes: [], definicion: "Plataforma que publica sitios web con arrastrar y soltar o desde GitHub.", mes: 9 },
  { termino: "Vercel", variantes: [], definicion: "Plataforma de deploy especializada en proyectos Next.js/React.", mes: 9 },
  { termino: "AWS", variantes: ["amazon web services"], definicion: "La nube de Amazon: el proveedor de servidores más grande del mundo.", mes: 9 },
  { termino: "EC2", variantes: [], definicion: "El servicio de AWS para rentar servidores virtuales.", mes: 9 },
  { termino: "S3", variantes: [], definicion: "El servicio de AWS para guardar archivos en la nube.", mes: 9 },
  { termino: "ARN", variantes: ["arns"], definicion: "Amazon Resource Name: el \"CURP\" de cada recurso en AWS — su identificador único.", mes: 9 },
  { termino: "variable de entorno", variantes: ["env", ".env"], definicion: "Dato de configuración (como una clave secreta) que vive fuera del código.", mes: 9 },
  { termino: "API key", variantes: ["clave api", "access token"], definicion: "Llave secreta que identifica a tu app ante un servicio. NUNCA se comparte ni se sube al código.", mes: 9 },
  { termino: "SSL", variantes: ["certificado", "tls"], definicion: "El cifrado que pone el candadito en tu sitio (el HTTPS).", mes: 9 },
  { termino: "Supabase", variantes: [], definicion: "Plataforma que te da base de datos, login y almacenamiento listos para usar.", mes: 10 },
  { termino: "Postgres", variantes: ["postgresql"], definicion: "La base de datos relacional open source más respetada del mundo.", mes: 10 },
  { termino: "RLS", variantes: ["row level security"], definicion: "Reglas de seguridad que controlan qué filas de la base puede ver cada usuario.", mes: 10 },
  { termino: "cifrado", variantes: ["encriptación", "encriptar"], definicion: "Convertir información en código ilegible para protegerla.", mes: 10 },
  { termino: "Stripe", variantes: [], definicion: "Pasarela de pagos global para cobrar con tarjeta en tu app.", mes: 10 },
  { termino: "Mercado Pago", variantes: ["mercadopago"], definicion: "La pasarela de pagos líder en Latinoamérica.", mes: 10 },
  { termino: "pasarela de pago", variantes: ["checkout"], definicion: "El sistema que procesa pagos con tarjeta de forma segura en tu app.", mes: 10 },
  { termino: "cron", variantes: ["cron job"], definicion: "Tarea programada que se ejecuta sola en horario fijo (\"todos los días a las 8am\").", mes: 11 },
  { termino: "bot", variantes: ["bots"], definicion: "Programa que conversa o actúa automáticamente (ej. un bot de WhatsApp).", mes: 11 },
  { termino: "workflow", variantes: ["flujo de trabajo"], definicion: "Cadena de pasos automatizados: \"cuando llegue X, haz Y, luego Z\".", mes: 11 },
  { termino: "n8n", variantes: ["zapier", "make"], definicion: "Herramientas para armar automatizaciones conectando apps sin programar todo a mano.", mes: 11 },
  { termino: "cola", variantes: ["queue"], definicion: "Fila de tareas pendientes que un sistema procesa en orden.", mes: 11 },
  { termino: "SaaS", variantes: [], definicion: "Software as a Service: software que se renta por suscripción (Netflix del software).", mes: 12 },
  { termino: "MVP", variantes: ["producto mínimo viable"], definicion: "La versión más simple de tu producto que ya resuelve el problema y se puede vender.", mes: 12 },
  { termino: "landing page", variantes: ["landing"], definicion: "Página única diseñada para convertir visitantes en clientes.", mes: 12 },
  { termino: "escalabilidad", variantes: ["escalar"], definicion: "Que tu sistema aguante crecer: de 10 usuarios a 10,000 sin morir.", mes: 12 },
  { termino: "etiqueta semántica", variantes: ["semántico"], definicion: "Etiqueta HTML que describe su contenido (header, nav, main) en vez de solo agruparlo.", mes: 3 },
  { termino: "modelo de caja", variantes: ["box model"], definicion: "Cómo el navegador calcula el espacio de cada elemento: content, padding, border y margin.", mes: 3 },
  { termino: "padding", variantes: [], definicion: "El espacio interno entre el contenido de un elemento y su borde.", mes: 3 },
  { termino: "margin", variantes: [], definicion: "El espacio externo alrededor de un elemento, que lo separa de los demás.", mes: 3 },
  { termino: "selector", variantes: ["selectores"], definicion: "La parte del CSS que indica a qué elemento o elementos se aplica una regla.", mes: 3 },
  { termino: "especificidad", variantes: [], definicion: "La regla que decide qué estilo gana cuando dos selectores chocan; la más específica manda.", mes: 3 },
  { termino: "cascada", variantes: [], definicion: "El orden en que el navegador aplica estilos: de reglas generales a específicas.", mes: 3 },
  { termino: "rem", variantes: [], definicion: "Unidad CSS relativa al tamaño de letra de la raíz del documento; la estándar para escalar.", mes: 3 },
  { termino: "viewport", variantes: [], definicion: "El área visible del navegador donde se pinta la página; cambia según el dispositivo.", mes: 3 },
  { termino: "flexbox", variantes: ["flex"], definicion: "Sistema CSS para alinear y distribuir elementos en una fila o columna.", mes: 3 },
  { termino: "grid", variantes: ["css grid"], definicion: "Sistema CSS para crear layouts en dos dimensiones: filas y columnas a la vez.", mes: 3 },
  { termino: "media query", variantes: [], definicion: "Regla CSS que aplica estilos según la condición del dispositivo (tamaño de pantalla, tema).", mes: 3 },
  { termino: "breakpoint", variantes: [], definicion: "El tamaño de pantalla donde un diseño cambia de disposición (ej. de 3 columnas a 1).", mes: 3 },
  { termino: "mobile-first", variantes: [], definicion: "Diseñar primero para pantallas chicas y después expandir para las grandes.", mes: 3 },
  { termino: "transición", variantes: ["transition"], definicion: "Animación CSS suave entre dos estados de un elemento al cambiar una propiedad.", mes: 3 },
  { termino: "querySelector", variantes: [], definicion: "Método de JavaScript que busca el primer elemento que coincide con un selector CSS.", mes: 3 },
  { termino: "evento", variantes: ["eventos"], definicion: "Algo que ocurre en la página (un clic, un teclazo) y JavaScript puede escuchar.", mes: 3 },
  { termino: "listener", variantes: ["event listener"], definicion: "La función que se registra para ejecutarse cuando ocurre un evento.", mes: 3 },
  { termino: "preventDefault", variantes: [], definicion: "Instrucción para cancelar el comportamiento nativo de un evento (como enviar un formulario).", mes: 3 },
  { termino: "innerHTML", variantes: [], definicion: "Propiedad para leer o escribir el HTML dentro de un elemento.", mes: 3 },
  { termino: "template literal", variantes: ["template string"], definicion: "String de JavaScript con acentos graves que permite incrustar variables con ${ }.", mes: 3 },
  { termino: "map", variantes: [], definicion: "Método de arreglo que transforma cada elemento y devuelve un arreglo nuevo.", mes: 3 },
  { termino: "filter", variantes: [], definicion: "Método de arreglo que devuelve solo los elementos que cumplen una condición.", mes: 3 },
  { termino: "localStorage", variantes: [], definicion: "Almacenamiento del navegador que persiste datos entre visitas, sin servidor.", mes: 3 },
  { termino: "asincronía", variantes: ["async"], definicion: "Que el código no se bloquea: arranca algo y sigue, para continuar cuando responda.", mes: 3 },
  { termino: "promesa", variantes: ["promise"], definicion: "Objeto que representa un valor futuro: pendiente, cumplida o rechazada.", mes: 3 },
  { termino: "async/await", variantes: [], definicion: "Sintaxis moderna para trabajar con promesas sin encadenar .then, leyendo casi como síncrono.", mes: 3 },
  { termino: "fetch", variantes: [], definicion: "Función de JavaScript para pedir datos a una URL (típicamente una API).", mes: 3 },
  { termino: "estado de carga", variantes: ["cargando"], definicion: "La fase en que una interfaz espera datos; debe mostrar algo (spinner, skeleton).", mes: 3 },
  { termino: "módulo", variantes: ["modules"], definicion: "Archivo JavaScript que exporta partes reutilizables e importa las de otros.", mes: 3 },
  { termino: "import/export", variantes: [], definicion: "Sintaxis para compartir código entre archivos JavaScript (módulos).", mes: 3 },
  { termino: "props", variantes: [], definicion: "Datos que un componente recibe de su padre para configurarse.", mes: 3 },
  { termino: "estado", variantes: ["state"], definicion: "Dato que vive dentro de un componente y, al cambiar, redibuja la interfaz.", mes: 3 },
  { termino: "hidratación", variantes: ["hydration"], definicion: "Cuando el HTML ya renderizado por el servidor cobra vida con JavaScript.", mes: 3 },
  { termino: "SSR", variantes: ["server side rendering"], definicion: "Renderizar la página en el servidor y enviar el HTML listo al navegador.", mes: 3 },
  { termino: "Open Graph", variantes: [], definicion: "Meta tags que controlan cómo se ve tu enlace al compartirse (imagen, título).", mes: 3 },
  { termino: "meta tag", variantes: ["meta"], definicion: "Etiqueta del <head> que da información sobre la página (título, descripción, SEO).", mes: 3 },
  { termino: "favicon", variantes: [], definicion: "El icono pequeño de la pestaña del navegador y de los marcadores.", mes: 3 },
  { termino: "lazy loading", variantes: [], definicion: "Cargar imágenes o secciones solo cuando el usuario está por verlas, no todas de golpe.", mes: 3 },
  { termino: "WebP", variantes: [], definicion: "Formato de imagen moderno que pesa menos que JPG o PNG con calidad similar.", mes: 3 }
];
